version: '3.9'

services:
  api:
    container_name: api
    image: frreimon/api:2.6
    restart: always
    ports:
      - "80:8000"
    volumes:
      - ./API/app:/code/app
    env_file:
      - .env
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - .env